name: "Saplings - Program Content Type"
description: "Provides the Program content type with all fields, display config, and SEO settings."
type: "Site"

recipes:
  - core/recipes/content_editor_role
  - saplings-content-base
  - saplings-component-types
  - saplings-fields-header
  - saplings-fields-seo

install:
  - node
  - metatag
  - schema_metatag
  - menu_ui
  - scheduler
config:
  actions:
    user.role.anonymous:
      createIfNotExists:
        id: anonymous
      grantPermissions:
        - "access_unpublished node event"
    user.role.content_editor:
      createIfNotExists:
        id: content_editor
      grantPermissions:
        - "access_unpublished node event"
        - "clone event content"
        - "create event content"
        - "create terms in sa_event_category"
        - "delete own event content"
        - "delete event revisions"
        - "edit any event content"
        - "edit own event content"
        - "edit terms in sa_event_category"
        - "revert event revisions"
        - "set event published on date"
        - "view any unpublished event content"
        - "view event revisions"
